# Server configuration
server.port=8080

# File Upload configurations
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Prediction ML Service (FastAPI) Endpoint Configuration
fastapi.ml.service.url=http://localhost:8000/ml/predict
